
require("remaps")
require("set")
require("plugins.telescope")
require("plugins.harpoon")
require("plugins.tree-sitter")
require("plugins.undotree")
require("plugins.lsp")
require("plugins.completions")
require("plugins.vim-tmux-nav")
